// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1OTDXWOrT__Vy02f0sCeyxiI81CcuGU',
    appId: '1:520177186090:web:2e693ec080b46d94869a53',
    messagingSenderId: '520177186090',
    projectId: 'bidbuyy',
    authDomain: 'bidbuyy.firebaseapp.com',
    storageBucket: 'bidbuyy.appspot.com',
    measurementId: 'G-D3J3GCCZLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ81Lgdi1d7ifKS7C-t1s8_5EWNivr_n8',
    appId: '1:520177186090:android:4b29ef01ef8bd923869a53',
    messagingSenderId: '520177186090',
    projectId: 'bidbuyy',
    storageBucket: 'bidbuyy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2KhyjYCAEQA7TBbmgdEavwi5ePo22wr8',
    appId: '1:520177186090:ios:465f04feb1fdd85a869a53',
    messagingSenderId: '520177186090',
    projectId: 'bidbuyy',
    storageBucket: 'bidbuyy.appspot.com',
    iosBundleId: 'com.example.bidbuyyweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2KhyjYCAEQA7TBbmgdEavwi5ePo22wr8',
    appId: '1:520177186090:ios:bbc685e1e4400f5d869a53',
    messagingSenderId: '520177186090',
    projectId: 'bidbuyy',
    storageBucket: 'bidbuyy.appspot.com',
    iosBundleId: 'com.example.bidbuyyweb.RunnerTests',
  );
}
